### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by slightlytyler** [jacobhausler/gestalt-list#3]
- [x] A Category belongs to a List
- [x] A Post can belong to a Category
- [x] A user should be able to query for Category on List
- [ ] A user should be able to see Posts belonging to a Category; `CategoryFeed`

**Comment by jacobhausler** [comment]
no categoryFeed required;

```
query{
  node(id:"id of List"){
    ...on Category{
      posts{
        edges{
          node{
            id
            title
            text
          }
        }
      }
    }
  }
}
```
